### ISSUE TITLE
Instructions to build

### ISSUE THREAD

**Issue by mariohackandglitch** [Steveice10/bannertool#1]
Hello, I tried to build this at my own, using Cmake. But after I try to compile, I get 59 errors and 29 warnings. Could you give any instructions? Or isn't this project finished?

**Comment by Steveice10** [comment]
You just need to run cmake to generate the Makefile, etc. and make to build the source. If that isn't working for you, I'll need more info, such as your OS and what errors you're encountering.

**Comment by mariohackandglitch** [comment]
I'm encountering erros after generating with CMake, in VisualStudio,
What I've done:
1 - Use Cmake to generate the sln, selecting Visual Studio 2013.
2 - Open the generated sln in Visual Studio
3 - Build

**Comment by Steveice10** [comment]
What are the errors? I don't use Visual Studio, so I don't know whether it builds or not.

**Comment by Lectem** [comment]
You are using variable length arrays, those are not in the c++ standard
https://github.com/Steveice10/bannertool/blob/master/source/cmd.cpp#L277
https://github.com/Steveice10/bannertool/blob/master/source/cmd.cpp#L279
and 
https://github.com/Steveice10/bannertool/blob/master/source/cmd.cpp#L233

**Comment by Steveice10** [comment]
Usage of variable length arrays should be gone.

**Comment by m1guelpf** [comment]
How do I install it on Ubuntu?
