### ISSUE TITLE
Remove Visibility from the home menu.

### ISSUE THREAD

**Issue by JumperGerald** [Steveice10/bannertool#10]
I am looking for a way to remove visibility from homebrew applications on the home menu. If you don't add the visibility flag to your application it seems to default to visible still. Any info would be appreciated.

**Comment by Steveice10** [comment]
Make sure you're using the latest build/source.

**Comment by JumperGerald** [comment]
What do I need to compile it on windows? I was getting gcc not recognized so I installed MinGw. Now I a get can not find -lpthead

**Comment by Steveice10** [comment]
I don't use Windows, so I can't really help you there. However, you can find pre-compiled builds here: https://github.com/Steveice10/buildtools/tree/master/3ds
