### ISSUE TITLE
Sound is set as beeps

### ISSUE THREAD

**Issue by thejsa** [Steveice10/bannertool#11]
Heya,
Any time I try to make a banner it invariably ends up with loud beeps as the sound effect (I use the -ca option with a [B]CWAV converted using the SDK tool.)
Here's the [B]CWAV in question (zipped because GitHub complains about unsupported file formats): [shulk.zip](https://github.com/Steveice10/bannertool/files/457322/shulk.zip)

**Comment by Steveice10** [comment]
Does the build in https://github.com/Steveice10/bannertool/issues/13 help?

**Comment by nbzwt** [comment]
I experienced the same issue, it seems to be unrelated to the cwav file I use.

**Comment by Steveice10** [comment]
Is this issue still present in this build of the latest source?

https://www.dropbox.com/s/jnu1184y259wwqj/bannertool.zip?dl=1

**Comment by TimmSkiller** [comment]
I'm having this issue with the latest release
