### ISSUE TITLE
Could not find WAV format chunk?

### ISSUE THREAD

**Issue by Gelums** [Steveice10/bannertool#12]
Trying to use a 2 second audio dialog of Glados from Portal saying "Oh, its you." but keep running into this error. Any help? I've asked  people on GBAtemp, but haven't found anything yet. 
This is the source of the audio file I am using
http://i1.theportalwiki.net/img/3/34/GLaDOS_chellgladoswakeup01.wav

**Comment by Steveice10** [comment]
Cannot reproduce. What platform are you using?
