### ISSUE TITLE
ERROR: Could not find WAV format chunk.

### ISSUE THREAD

**Issue by gg30433043** [Steveice10/bannertool#13]
This error occurs when I Try to convert a wav to a cwav

C:\Users\XXXX\Documents\3ds THEMES\Custom Theme\YATA+\bannertool-master>bannertool.exe makecwav -i Bing.wav -o Bing.cwav
ERROR: Could not find WAV format chunk.

**Comment by Steveice10** [comment]
See https://github.com/Steveice10/bannertool/issues/12

Although the knowledge that it's happening on Windows helps, thanks.

**Comment by Steveice10** [comment]
Actually, considering this issue is actually active... can you test this build and see what the result is?

https://www.dropbox.com/s/v0gob6juyyblvjj/bannertool.exe?dl=1

**Comment by Steveice10** [comment]
Is this issue still present in this build of the latest source?

https://www.dropbox.com/s/jnu1184y259wwqj/bannertool.zip?dl=1

**Comment by T3CHNOLOG1C** [comment]
@Steveice10 if you can supply me a build i can test this, im trying to do this myself

**Comment by T3CHNOLOG1C** [comment]
nvm it works with latest release

**Comment by Steveice10** [comment]
Good to hear, thanks.
