### ISSUE TITLE
Compilation of the program fails with error: expected primary-expression before ‘)’ token

### ISSUE THREAD

**Issue by Fisk24** [Steveice10/bannertool#14]
source/cmd.cpp: In function ‘void cmd_print_usage(const string&)’:
    source/cmd.cpp:393:51: error: expected primary-expression before ‘,’ token
    printf("bannertool v%d.%d.%d\n", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
                                                   ^
    source/cmd.cpp:393:66: error: expected primary-expression before ‘,’ token
         printf("bannertool v%d.%d.%d\n", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
                                                                  ^
    source/cmd.cpp:393:81: error: expected primary-expression before ‘)’ token
         printf("bannertool v%d.%d.%d\n", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
                                                                                 ^
    make: *** [buildtools/make_base:590: build/linux-x86_64/source/cmd.o] Error 1

**Comment by Steveice10** [comment]
Make sure you have git and cloned the repository.

**Comment by Xtansia** [comment]
There are no tags on the repository, so `git describe` is failing.

**Comment by Steveice10** [comment]
For some reason the tag didn't push; it's fixed now.

**Comment by Fisk24** [comment]
hey sorry for the late response. thanks for the info
