### ISSUE TITLE
Undeclared Variables - Make fail

### ISSUE THREAD

**Issue by ObscenityIB** [Steveice10/bannertool#15]
Using Windows 10 x64.

Performed steps to produce issue:

1

    C:\Users\Obscenity\Documents\DEV\git\bannertool-dev>git pull origin master
    remote: Counting objects: 22, done.
    remote: Total 22 (delta 6), reused 6 (delta 6), pack-reused 16
    Unpacking objects: 100% (22/22), done.
    From https://github.com/Steveice10/bannertool
     * branch            master     -> FETCH_HEAD
       327ea4d..e24233e  master     -> origin/master
    Updating 327ea4d..e24233e
    Fast-forward
     .gitignore     |  1 +
     Makefile       | 30 ++++++++----------------------
     buildtools     |  2 +-
     source/cmd.cpp |  1 +
     4 files changed, 11 insertions(+), 23 deletions(-)

2

    C:\Users\Obscenity\Documents\DEV\git\bannertool-dev>make
    fatal: No names found, cannot describe anything.
    build/source/cmd.o
    source/cmd.cpp: In function 'void cmd_print_usage(const string&)':
    source/cmd.cpp:393:38: error: 'VERSION_MAJOR' was not declared in this scope
         printf("bannertool v%d.%d.%d\n", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
                                      ^
    source/cmd.cpp:393:53: error: 'VERSION_MINOR' was not declared in this scope
         printf("bannertool v%d.%d.%d\n", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
                                                     ^
    source/cmd.cpp:393:68: error: 'VERSION_MICRO' was not declared in this scope
         printf("bannertool v%d.%d.%d\n", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
                                                                    ^
    At global scope:
    cc1plus.exe: warning: unrecognized command line option '-Wno-misleading-indentation'
    make: *** [build/source/cmd.o] Error 1

Resolution:

Original cmd.cpp

    void cmd_print_usage(const std::string& executedFrom) {
        printf("bannertool v%d.%d.%d\n", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
        printf("Usage: %s <command> <args>\n", executedFrom.c_str());
        cmd_print_commands();
    }

Modified

    void cmd_print_usage(const std::string& executedFrom) {
        int VERSION_MAJOR = 1;
        int VERSION_MINOR = 0;
        int VERSION_MICRO = 0;
        printf("bannertool v%d.%d.%d\n", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
        printf("Usage: %s <command> <args>\n", executedFrom.c_str());
        cmd_print_commands();
    }

Result:

    C:\Users\Obscenity\Documents\DEV\git\bannertool-dev>make
    fatal: No names found, cannot describe anything.
    build/source/cmd.o
    output/bannertool.exe
    output/bannertool.zip

**Comment by Steveice10** [comment]
Make sure to pull the tags too; those are defined by the Make file based on got tags.
