### ISSUE TITLE
No banner - results in an infinite home menu crash

### ISSUE THREAD

**Issue by joel16** [Steveice10/bannertool#16]
Using the latest commit of bannertool breaks the banner if you install the CIA. Here's the makefile I'm using if you were interested: https://github.com/joel16/3DShell/blob/master/Makefile

The only way I had to fix this was by removing the SD card, booting from CTRNAND and then re-inserting the SD and deleting the title from FBI. Please look into this. Not sure why this happens but I realized this after installing one of my recent travis build. (My travis build config makes sure to use everything from the very last commit)

**Comment by Steveice10** [comment]
Good catch, should be fixed now.
