### ISSUE TITLE
Not an issue, but, how to use it?

### ISSUE THREAD

**Issue by placeboyue** [Steveice10/bannertool#19]
i've spent a whole day looking for clues on how to make banners, i finally managed to get the BCMDL files and all.. but i have no clue on how to do anything with them, how to use bannertool to add it to my CIA or whatever.

A little insight for "the users" might be handy. 

thank you

**Comment by Steveice10** [comment]
bannertool's usage message provides a full list of available commands and their arguments, and has no part in adding the created banner to a CIA. You'll have to check makerom for that.
