### ISSUE TITLE
lz11 compression is broken

### ISSUE THREAD

**Issue by piratesephiroth** [Steveice10/bannertool#2]
Files become corrupted if they're bigger than 128KB

![over 128KB error image](http://i.imgur.com/Ut0i96q.png)

**Comment by Steveice10** [comment]
Just to clarify, you are trying to compress a file, right? bannertool doesn't support decompression, as your image suggests you are trying to do.

**Comment by piratesephiroth** [comment]
I used other tool to decompress it..
I'm just telling you bannertool's compression is broken.

**Comment by Steveice10** [comment]
So, "original file" is the bannertool output, and "decompressed file" is the other tool's output? Then are you sure the other tool isn't decompressing wrong?

**Comment by piratesephiroth** [comment]
Yeah, "original" is the file before compression.
I then compress it with bannertool and extract it with other tool, obtaining the "decompressed" ione, with all bytes over 128KB being zeros.

And the decompressing tools work fine. I used [LZX](http://www.romhacking.net/utilities/826/) but you could also build a banner with bannertool and extract the decompressed cgfx with 3DS Explorer, obtaining the same broken file.

**Comment by Steveice10** [comment]
Works fine for me with a randomly generated 162.6KB file.

**Comment by piratesephiroth** [comment]
Try with [this randomly generated file.](https://my.mixtape.moe/rwngtw.bin)
It never gets properly compressed.

**Comment by piratesephiroth** [comment]
[this](https://my.mixtape.moe/vozjco.bin) is what I get after decompression

**Comment by Steveice10** [comment]
Works fine for me. What OS/architecture are you on?

**Comment by piratesephiroth** [comment]
Windows 8.1, x64

**Comment by piratesephiroth** [comment]
info about the compiled exe

"[info](http://i.imgur.com/Nabomn5.png)

**Comment by Steveice10** [comment]
I am able to reproduce it on Windows, but I'm not sure why this is the case yet.

**Comment by Steveice10** [comment]
Is this issue still present in this build of the latest source?

https://www.dropbox.com/s/jnu1184y259wwqj/bannertool.zip?dl=1
