### ISSUE TITLE
bannertool from release require glibc 2.29

### ISSUE THREAD

**Issue by ShockwaveNN** [Steveice10/bannertool#21]
Current version `bannertool` downloaded from Github Release require glibc 2.29
Current stable version of glibc on Ubuntu 18.04 is [2.28](https://packages.ubuntu.com/source/bionic/glibc)
This Dockerfile result error:
```
FROM ubuntu:18.10

RUN apt-get -y update && \
    apt-get install -y wget unzip

RUN wget https://github.com/Steveice10/bannertool/releases/latest/download/bannertool.zip && \
    unzip -p bannertool.zip linux-x86_64/bannertool > /bin/bannertool && \
    chmod +x /bin/bannertool && \
    rm bannertool.zip
RUN bannertool
```

Error:
```
Step 4/4 : RUN bannertool
 ---> Running in 77fd8579efa8
bannertool: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by bannertool)
```

I think it's a good idea to compile release version with glibc 2.28 (for example using Dockerfile I provided at https://github.com/Steveice10/bannertool/pull/20

**Comment by Steveice10** [comment]
I don't believe I'm explicitly requiring any specific version of glibc anywhere. If there's an issue with the Dockerfile feel free to fix it, I just merged in the pull request you sent as-is.

**Comment by ShockwaveNN** [comment]
@Steveice10 Yeah, thanks. I got one at hand, if you wanna - I can attach it
