### ISSUE TITLE
Doesnt compile as target 3ds

### ISSUE THREAD

**Issue by Ntemis** [Steveice10/bannertool#22]
demetris@demetris-TA770E3:~/bannertool$ make TARGET=3DS
Building for 3DS...
build/3ds-arm/source/pc/stb_vorbis.o
build/3ds-arm/source/pc/stb_image.o
build/3ds-arm/source/main.o
build/3ds-arm/source/cmd.o
source/cmd.cpp: In function 'void* load_image(const string&, u32, u32)':
source/cmd.cpp:124:47: warning: format '%d' expects argument of type 'int', but argument 2 has type 'u32' {aka 'long unsigned int'} [-Wformat=]
  124 |         printf("ERROR: Image must be exactly %d x %d in size.\n", width, height);
      |                                              ~^                   ~~~~~
      |                                               |                   |
      |                                               int                 u32 {aka long unsigned int}
      |                                              %ld
source/cmd.cpp:124:52: warning: format '%d' expects argument of type 'int', but argument 3 has type 'u32' {aka 'long unsigned int'} [-Wformat=]
  124 |         printf("ERROR: Image must be exactly %d x %d in size.\n", width, height);
      |                                                   ~^                     ~~~~~~
      |                                                    |                     |
      |                                                    int                   u32 {aka long unsigned int}
      |                                                   %ld
build/3ds-arm/source/pc/wav.o
build/3ds-arm/source/3ds/cwav.o
build/3ds-arm/source/3ds/cbmd.o
build/3ds-arm/source/3ds/lz11.o
output/3ds-arm/bannertool.elf
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: /opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/lib/armv6k/fpu/3dsx_crt0.o: in function `startup':
(.crt0+0x38): undefined reference to `initSystem'
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: /opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/lib/armv6k/fpu/3dsx_crt0.o: in function `ClrLoop':
(.crt0+0x84): undefined reference to `__system_argc'
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: (.crt0+0x88): undefined reference to `__system_argv'
collect2: error: ld returned 1 exit status
buildtools/make_base:697: recipe for target 'output/3ds-arm/bannertool.elf' failed
make: *** [output/3ds-arm/bannertool.elf] Error 1

**Comment by Steveice10** [comment]
bannertool is a command line tool meant to run on the PC, not a 3DS.
