### ISSUE TITLE
ERROR: Could not find WAV data chunk.

### ISSUE THREAD

**Issue by Rinnegatamante** [Steveice10/bannertool#5]
Tried to create a banner with a WAV files of about 1 sec of duration and got this error.
File was encoded with Audacity as Stereo File with 32k as samplerate.

Trying to opening the wav file with an HEX editor resulted in data chunk header starting at offset 0x7A if can be useful to know.

Ask me for the entire file if you need it and i'll attach it.

**Comment by cantenna** [comment]
having the same issue as stated above.

**Comment by Steveice10** [comment]
Just committed a change, try building and see if it fixes the problem.

**Comment by Xavyrr** [comment]
I have this issue as well with files a 32k sample rate, setting it to 41k makes a file, but replays as audio garbage (screeching sounds of death). re-extracting the .bcwav and attempting to play it results in it foobar stating it's corrupted.
